apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: toggle-master
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczo4ak5mNDh0VXdJMzVjUXc0Qzcya0B0YXJnZXRpbmctZGIuY3c5d3dtdWM2Z2Z2LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3RhcmdldGluZ19kYg==
  AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZTo4MDAx
