apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Aponta para o base comum
resources:
  - ../../base

# Exemplo de customização exclusiva de prod
patches:
  - target:
      kind: Deployment
      name: targeting-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
