apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 1. Infraestrutura base (Namespace, Ingress, Secrets globais)
  - ../../infrastructure/overlays/prod

  # 2. Microsserviços
  - ../../apps/auth-service/overlays/prod
  - ../../apps/flag-service/overlays/prod
  # Adicione os próximos microsserviços aqui conforme forem criados:
  # - ../../apps/targeting-service/overlays/prod
  # - ../../apps/evaluation-service/overlays/prod
  # - ../../apps/analytics-service/overlays/prod
