apiVersion: v1
kind: Secret
metadata:
  name: global-aws-secret
  namespace: toggle-master
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVFZUlJPWDRKWllPNEpOUFU=
  AWS_SECRET_ACCESS_KEY: cjZ5ZGZXMjlvV2w5L3pUSlNaOHdTZmZMSHk2OVEyZEtGZUJRQzhyNw==
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMDUyNzE3MDc2MjQzL015UXVldWU=
  AWS_REGION: dXMtZWFzdC0x
