apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toggle-master

resources:
- configmap.yml
- deployment.yml
- externalsecret.yml
- service.yml


# ============================================
# IMAGENS
# ============================================
# Configuração de imagens Docker
# Permite substituir tags sem modificar os YAMLs
# O "name" deve corresponder ao placeholder no deployment.yaml
# O "newName" é a imagem real no ECR
images:
- name: fase2-auth-service
  newName: 052717076243.dkr.ecr.us-east-2.amazonaws.com/super-app/auth-service-default
  newTag: bc13dcd058908a87edecde32cbddbd3d97c2d7e0
