apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: toggle-master
type: Opaque
stringData:
  DATABASE_URL: "postgres://togglemaster_user:minhaSenhaSegura123@host.docker.internal:5432/auth_db?sslmode=disable"
  MASTER_KEY: "admin-secreto-123"
