apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: toggle-master
type: Opaque
stringData:
  DATABASE_URL: "postgres://jojoadmin:SenhaSuperSegura123!@jojo-adventure-db.c98a0e0syqch.us-east-2.rds.amazonaws.com:5432/auth_db?sslmode=require"
  MASTER_KEY: "admin-secreto-123"


