apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: targeting-service-secrets
  namespace: toggle-master
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: targeting-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /targeting-service/database_url
