apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: evaluation-service-secrets
  namespace: toggle-master
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: evaluation-service-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: /evaluation-service/redis_url
    - secretKey: AWS_SQS_URL
      remoteRef:
        key: /evaluation-service/sqs_url
    - secretKey: SERVICE_API_KEY
      remoteRef:
        key: /evaluation-service/service_api_key
