apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: analytics-service-secrets
  namespace: toggle-master
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: analytics-service-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_DYNAMODB_TABLE
      remoteRef:
        key: /analytics-service/dynamodb_table
    - secretKey: AWS_SQS_URL
      remoteRef:
        key: /analytics-service/sqs_url
