apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service-sa
  namespace: toggle-master
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::052717076243:role/super-app-v1-analytics-irsa-role
