apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: toggle-master
type: Opaque
data:
  REDIS_URL: cmVkaXNzOi8vdG9nZ2xlLW1hc3Rlci12cGMtZXFvaXM0LnNlcnZlcmxlc3MudXNlMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=
  FLAG_SERVICE_URL: aHR0cDovL2ZsYWctc2VydmljZTo4MDAy
  TARGETING_SERVICE_URL: aHR0cDovL3RhcmdldGluZy1zZXJ2aWNlOjgwMDM=
  SERVICE_API_KEY: dG1fa2V5XzZiNTIwZjc0OGJhMjlmMTg3NzFmZjY1M2VhMDQ0NDcyM2NjYzBjYWNkMjI3NmMyYTZkMjU5MTlhNGQyNzM3YmI=
